# Generated by Django 4.2.3 on 2023-07-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("general_registration", models.CharField(max_length=9)),
                ("document", models.CharField(max_length=11)),
                ("birth_date", models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("B", "Basic"), ("M", "Mid"), ("A", "Advance")],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
