# Generated by Django 3.2.14 on 2023-07-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('N', 'Nocturnal')], default='M', max_length=1)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
                ('document_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
            ],
        ),
    ]
