# Generated by Django 3.2.14 on 2023-07-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='document_student',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='course_code',
            new_name='curso',
        ),
    ]
