# Generated by Django 3.2.14 on 2023-07-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20230731_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='aluno',
            new_name='student',
        ),
    ]
